interface CountryOption {
  value: string;
  label: string;
  flag: string;
}

export const countryOptions: CountryOption[] = [
  { value: 'AF', label: 'Any', flag: 'AF' },
  { value: 'AF', label: 'Afghanistan', flag: 'AF' },
  { value: 'AL', label: 'Albania', flag: 'AL' },
  { value: 'DZ', label: 'Algeria', flag: 'DZ' },
  { value: 'AS', label: 'American Samoa', flag: 'AS' },
  { value: 'AD', label: 'Andorra', flag: 'AD' },
  { value: 'AO', label: 'Angola', flag: 'AO' },
  { value: 'AI', label: 'Anguilla', flag: 'AI' },
  { value: 'AQ', label: 'Antarctica', flag: 'AQ' },
  { value: 'AG', label: 'Antigua and Barbuda', flag: 'AG' },
  { value: 'AR', label: 'Argentina', flag: 'AR' },
  { value: 'AM', label: 'Armenia', flag: 'AM' },
  { value: 'AW', label: 'Aruba', flag: 'AW' },
  { value: 'AU', label: 'Australia', flag: 'AU' },
  { value: 'AT', label: 'Austria', flag: 'AT' },
  { value: 'AZ', label: 'Azerbaijan', flag: 'AZ' },
  { value: 'BS', label: 'Bahamas', flag: 'BS' },
  { value: 'BH', label: 'Bahrain', flag: 'BH' },
  { value: 'BD', label: 'Bangladesh', flag: 'BD' },
  { value: 'BB', label: 'Barbados', flag: 'BB' },
  { value: 'BY', label: 'Belarus', flag: 'BY' },
  { value: 'BE', label: 'Belgium', flag: 'BE' },
  { value: 'BZ', label: 'Belize', flag: 'BZ' },
  { value: 'BJ', label: 'Benin', flag: 'BJ' },
  { value: 'BM', label: 'Bermuda', flag: 'BM' },
  { value: 'BT', label: 'Bhutan', flag: 'BT' },
  { value: 'BO', label: 'Bolivia', flag: 'BO' },
  { value: 'BQ', label: 'Bonaire', flag: 'BQ' },
  { value: 'BA', label: 'Bosnia and Herzegovina', flag: 'BA' },
  { value: 'BW', label: 'Botswana', flag: 'BW' },
  { value: 'BV', label: 'Bouvet Island', flag: 'BV' },
  { value: 'BR', label: 'Brazil', flag: 'BR' },
  { value: 'IO', label: 'British Indian Ocean Territory', flag: 'IO' },
  { value: 'BN', label: 'Brunei Darussalam', flag: 'BN' },
  { value: 'BG', label: 'Bulgaria', flag: 'BG' },
  { value: 'BF', label: 'Burkina Faso', flag: 'BF' },
  { value: 'BI', label: 'Burundi', flag: 'BI' },
  { value: 'CV', label: 'Cabo Verde', flag: 'CV' },
  { value: 'KH', label: 'Cambodia', flag: 'KH' },
  { value: 'CM', label: 'Cameroon', flag: 'CM' },
  { value: 'CA', label: 'Canada', flag: 'CA' },
  { value: 'KY', label: 'Cayman Islands', flag: 'KY' },
  { value: 'CF', label: 'Central African Republic', flag: 'CF' },
  { value: 'TD', label: 'Chad', flag: 'TD' },
  { value: 'CL', label: 'Chile', flag: 'CL' },
  { value: 'CN', label: 'China', flag: 'CN' },
  { value: 'CX', label: 'Christmas Island', flag: 'CX' },
  { value: 'CC', label: 'Cocos Keeling Islands', flag: 'CC' },
  { value: 'CO', label: 'Colombia', flag: 'CO' },
  { value: 'KM', label: 'Comoros', flag: 'KM' },
  { value: 'CG', label: 'Congo', flag: 'CG' },
  { value: 'CK', label: 'Cook Islands', flag: 'CK' },
  { value: 'CR', label: 'Costa Rica', flag: 'CR' },
  { value: 'HR', label: 'Croatia', flag: 'HR' },
  { value: 'CU', label: 'Cuba', flag: 'CU' },
  { value: 'CW', label: 'Curaçao', flag: 'CW' },
  { value: 'CY', label: 'Cyprus', flag: 'CY' },
  { value: 'CZ', label: 'Czechia', flag: 'CZ' },
  { value: 'CI', label: "Côte d'Ivoire", flag: 'CI' },
  { value: 'DK', label: 'Denmark', flag: 'DK' },
  { value: 'DJ', label: 'Djibouti', flag: 'DJ' },
  { value: 'DM', label: 'Dominica', flag: 'DM' },
  { value: 'DO', label: 'Dominican Republic', flag: 'DO' },
  { value: 'EC', label: 'Ecuador', flag: 'EC' },
  { value: 'EG', label: 'Egypt', flag: 'EG' },
  { value: 'SV', label: 'El Salvador', flag: 'SV' },
  { value: 'GQ', label: 'Equatorial Guinea', flag: 'GQ' },
  { value: 'ER', label: 'Eritrea', flag: 'ER' },
  { value: 'EE', label: 'Estonia', flag: 'EE' },
  { value: 'SZ', label: 'Eswatini', flag: 'SZ' },
  { value: 'ET', label: 'Ethiopia', flag: 'ET' },
  { value: 'FK', label: 'Falkland Islands Malvinas', flag: 'FK' },
  { value: 'FO', label: 'Faroe Islands', flag: 'FO' },
  { value: 'FJ', label: 'Fiji', flag: 'FJ' },
  { value: 'FI', label: 'Finland', flag: 'FI' },
  { value: 'FR', label: 'France', flag: 'FR' },
  { value: 'GF', label: 'French Guiana', flag: 'GF' },
  { value: 'PF', label: 'French Polynesia', flag: 'PF' },
  { value: 'TF', label: 'French Southern Territories', flag: 'TF' },
  { value: 'GA', label: 'Gabon', flag: 'GA' },
  { value: 'GM', label: 'Gambia', flag: 'GM' },
  { value: 'GE', label: 'Georgia', flag: 'GE' },
  { value: 'DE', label: 'Germany', flag: 'DE' },
  { value: 'GH', label: 'Ghana', flag: 'GH' },
  { value: 'GI', label: 'Gibraltar', flag: 'GI' },
  { value: 'GR', label: 'Greece', flag: 'GR' },
  { value: 'GL', label: 'Greenland', flag: 'GL' },
  { value: 'GD', label: 'Grenada', flag: 'GD' },
  { value: 'GP', label: 'Guadeloupe', flag: 'GP' },
  { value: 'GU', label: 'Guam', flag: 'GU' },
  { value: 'GT', label: 'Guatemala', flag: 'GT' },
  { value: 'GG', label: 'Guernsey', flag: 'GG' },
  { value: 'GN', label: 'Guinea', flag: 'GN' },
  { value: 'GW', label: 'Guinea-Bissau', flag: 'GW' },
  { value: 'GY', label: 'Guyana', flag: 'GY' },
  { value: 'HT', label: 'Haiti', flag: 'HT' },
  { value: 'HM', label: 'Heard Island and McDonald Islands', flag: 'HM' },
  { value: 'VA', label: 'Holy See Vatican City State', flag: 'VA' },
  { value: 'HN', label: 'Honduras', flag: 'HN' },
  { value: 'HK', label: 'Hong Kong', flag: 'HK' },
  { value: 'HU', label: 'Hungary', flag: 'HU' },
  { value: 'IS', label: 'Iceland', flag: 'IS' },
  { value: 'IN', label: 'India', flag: 'IN' },
  { value: 'ID', label: 'Indonesia', flag: 'ID' },
  { value: 'IR', label: 'Iran, Islamic Republic of', flag: 'IR' },
  { value: 'IQ', label: 'Iraq', flag: 'IQ' },
  { value: 'IE', label: 'Ireland', flag: 'IE' },
  { value: 'IM', label: 'Isle of Man', flag: 'IM' },
  { value: 'IL', label: 'Israel', flag: 'IL' },
  { value: 'IT', label: 'Italy', flag: 'IT' },
  { value: 'JM', label: 'Jamaica', flag: 'JM' },
  { value: 'JP', label: 'Japan', flag: 'JP' },
  { value: 'JE', label: 'Jersey', flag: 'JE' },
  { value: 'JO', label: 'Jordan', flag: 'JO' },
  { value: 'KZ', label: 'Kazakhstan', flag: 'KZ' },
  { value: 'KE', label: 'Kenya', flag: 'KE' },
  { value: 'KI', label: 'Kiribati', flag: 'KI' },
  { value: 'KR', label: 'Korea', flag: 'KR' },
  { value: 'KW', label: 'Kuwait', flag: 'KW' },
  { value: 'KG', label: 'Kyrgyzstan', flag: 'KG' },
  { value: 'LA', label: "Lao People's Democratic Republic", flag: 'LA' },
  { value: 'LV', label: 'Latvia', flag: 'LV' },
  { value: 'LB', label: 'Lebanon', flag: 'LB' },
  { value: 'LS', label: 'Lesotho', flag: 'LS' },
  { value: 'LR', label: 'Liberia', flag: 'LR' },
  { value: 'LY', label: 'Libya', flag: 'LY' },
  { value: 'LI', label: 'Liechtenstein', flag: 'LI' },
  { value: 'LT', label: 'Lithuania', flag: 'LT' },
  { value: 'LU', label: 'Luxembourg', flag: 'LU' },
  { value: 'MO', label: 'Macao', flag: 'MO' },
  { value: 'MG', label: 'Madagascar', flag: 'MG' },
  { value: 'MW', label: 'Malawi', flag: 'MW' },
  { value: 'MY', label: 'Malaysia', flag: 'MY' },
  { value: 'MV', label: 'Maldives', flag: 'MV' },
  { value: 'ML', label: 'Mali', flag: 'ML' },
  { value: 'MT', label: 'Malta', flag: 'MT' },
  { value: 'MH', label: 'Marshall Islands', flag: 'MH' },
  { value: 'MQ', label: 'Martinique', flag: 'MQ' },
  { value: 'MR', label: 'Mauritania', flag: 'MR' },
  { value: 'MU', label: 'Mauritius', flag: 'MU' },
  { value: 'YT', label: 'Mayotte', flag: 'YT' },
  { value: 'MX', label: 'Mexico', flag: 'MX' },
  { value: 'FM', label: 'Micronesia', flag: 'FM' },
  { value: 'MD', label: 'Moldova', flag: 'MD' },
  { value: 'MC', label: 'Monaco', flag: 'MC' },
  { value: 'MN', label: 'Mongolia', flag: 'MN' },
  { value: 'ME', label: 'Montenegro', flag: 'ME' },
  { value: 'MS', label: 'Montserrat', flag: 'MS' },
  { value: 'MA', label: 'Morocco', flag: 'MA' },
  { value: 'MZ', label: 'Mozambique', flag: 'MZ' },
  { value: 'MM', label: 'Myanmar', flag: 'MM' },
  { value: 'NA', label: 'Namibia', flag: 'NA' },
  { value: 'NR', label: 'Nauru', flag: 'NR' },
  { value: 'NP', label: 'Nepal', flag: 'NP' },
  { value: 'NL', label: 'Netherlands', flag: 'NL' },
  { value: 'NC', label: 'New Caledonia', flag: 'NC' },
  { value: 'NZ', label: 'New Zealand', flag: 'NZ' },
  { value: 'NI', label: 'Nicaragua', flag: 'NI' },
  { value: 'NE', label: 'Niger', flag: 'NE' },
  { value: 'NG', label: 'Nigeria', flag: 'NG' },
  { value: 'NU', label: 'Niue', flag: 'NU' },
  { value: 'NF', label: 'Norfolk Island', flag: 'NF' },
  { value: 'MK', label: 'North Macedonia', flag: 'MK' },
  { value: 'MP', label: 'Northern Mariana Islands', flag: 'MP' },
  { value: 'NO', label: 'Norway', flag: 'NO' },
  { value: 'OM', label: 'Oman', flag: 'OM' },
  { value: 'PK', label: 'Pakistan', flag: 'PK' },
  { value: 'PW', label: 'Palau', flag: 'PW' },
  { value: 'PS', label: 'Palestine', flag: 'PS' },
  { value: 'PA', label: 'Panama', flag: 'PA' },
  { value: 'PG', label: 'Papua New Guinea', flag: 'PG' },
  { value: 'PY', label: 'Paraguay', flag: 'PY' },
  { value: 'PE', label: 'Peru', flag: 'PE' },
  { value: 'PH', label: 'Philippines', flag: 'PH' },
  { value: 'PN', label: 'Pitcairn', flag: 'PN' },
  { value: 'PL', label: 'Poland', flag: 'PL' },
  { value: 'PT', label: 'Portugal', flag: 'PT' },
  { value: 'PR', label: 'Puerto Rico', flag: 'PR' },
  { value: 'QA', label: 'Qatar', flag: 'QA' },
  { value: 'RO', label: 'Romania', flag: 'RO' },
  { value: 'RU', label: 'Russian Federation', flag: 'RU' },
  { value: 'RW', label: 'Rwanda', flag: 'RW' },
  { value: 'RE', label: 'Réunion', flag: 'RE' },
  { value: 'BL', label: 'Saint Barthélemy', flag: 'BL' },
  { value: 'KN', label: 'Saint Kitts and Nevis', flag: 'KN' },
  { value: 'LC', label: 'Saint Lucia', flag: 'LC' },
  { value: 'MF', label: 'Saint Martin French part', flag: 'MF' },
  { value: 'PM', label: 'Saint Pierre and Miquelon', flag: 'PM' },
  { value: 'VC', label: 'Saint Vincent and the Grenadines', flag: 'VC' },
  { value: 'WS', label: 'Samoa', flag: 'WS' },
  { value: 'SM', label: 'San Marino', flag: 'SM' },
  { value: 'ST', label: 'Sao Tome and Principe', flag: 'ST' },
  { value: 'SA', label: 'Saudi Arabia', flag: 'SA' },
  { value: 'SN', label: 'Senegal', flag: 'SN' },
  { value: 'RS', label: 'Serbia', flag: 'RS' },
  { value: 'SC', label: 'Seychelles', flag: 'SC' },
  { value: 'SL', label: 'Sierra Leone', flag: 'SL' },
  { value: 'SG', label: 'Singapore', flag: 'SG' },
  { value: 'SX', label: 'Sint Maarten Dutch part', flag: 'SX' },
  { value: 'SK', label: 'Slovakia', flag: 'SK' },
  { value: 'SI', label: 'Slovenia', flag: 'SI' },
  { value: 'SB', label: 'Solomon Islands', flag: 'SB' },
  { value: 'SO', label: 'Somalia', flag: 'SO' },
  { value: 'ZA', label: 'South Africa', flag: 'ZA' },
  { value: 'ES', label: 'Spain', flag: 'ES' },
  { value: 'LK', label: 'Sri Lanka', flag: 'LK' },
  { value: 'SD', label: 'Sudan', flag: 'SD' },
  { value: 'SR', label: 'Suriname', flag: 'SR' },
  { value: 'SJ', label: 'Svalbard and Jan Mayen', flag: 'SJ' },
  { value: 'SE', label: 'Sweden', flag: 'SE' },
  { value: 'CH', label: 'Switzerland', flag: 'CH' },
  { value: 'SY', label: 'Syrian Arab Republic', flag: 'SY' },
  { value: 'TW', label: 'Taiwan, Province of China', flag: 'TW' },
  { value: 'TJ', label: 'Tajikistan', flag: 'TJ' },
  { value: 'TZ', label: 'Tanzania', flag: 'TZ' },
  { value: 'TH', label: 'Thailand', flag: 'TH' },
  { value: 'TL', label: 'Timor-Leste', flag: 'TL' },
  { value: 'TG', label: 'Togo', flag: 'TG' },
  { value: 'TK', label: 'Tokelau', flag: 'TK' },
  { value: 'TO', label: 'Tonga', flag: 'TO' },
  { value: 'TT', label: 'Trinidad and Tobago', flag: 'TT' },
  { value: 'TN', label: 'Tunisia', flag: 'TN' },
  { value: 'TR', label: 'Turkey', flag: 'TR' },
  { value: 'TM', label: 'Turkmenistan', flag: 'TM' },
  { value: 'TC', label: 'Turks and Caicos Islands', flag: 'TC' },
  { value: 'TV', label: 'Tuvalu', flag: 'TV' },
  { value: 'UG', label: 'Uganda', flag: 'UG' },
  { value: 'UA', label: 'Ukraine', flag: 'UA' },
  { value: 'AE', label: 'United Arab Emirates', flag: 'AE' },
  { value: 'GB', label: 'United Kingdom', flag: 'GB' },
  { value: 'US', label: 'United States', flag: 'US' },
  { value: 'UY', label: 'Uruguay', flag: 'UY' },
  { value: 'UZ', label: 'Uzbekistan', flag: 'UZ' },
  { value: 'VU', label: 'Vanuatu', flag: 'VU' },
  { value: 'VE', label: 'Venezuela', flag: 'VE' },
  { value: 'VN', label: 'Vietnam', flag: 'VN' },
  { value: 'VG', label: 'Virgin Islands, British', flag: 'VG' },
  { value: 'VI', label: 'Virgin Islands, U.S.', flag: 'VI' },
  { value: 'WF', label: 'Wallis and Futuna', flag: 'WF' },
  { value: 'EH', label: 'Western Sahara', flag: 'EH' },
  { value: 'YE', label: 'Yemen', flag: 'YE' },
  { value: 'ZM', label: 'Zambia', flag: 'ZM' },
  { value: 'ZW', label: 'Zimbabwe', flag: 'ZW' },
  { value: 'AX', label: 'Åland Islands', flag: 'AX' },
];

