import type { CurrencyOption } from "./type";


export const currencyOptions: CurrencyOption[] = [
  { value: 'AFN', label: 'AFN - (Afghani)' },
  { value: 'ALL', label: 'ALL - (Lek)' },
  { value: 'DZD', label: 'DZD - (Dinar)' },
  { value: 'AOA', label: 'AOA - (Kwanza)' },
  { value: 'ARS', label: 'ARS - (Peso)' },
  { value: 'AMD', label: 'AMD - (Dram)' },
  { value: 'AWG', label: 'AWG - (Florin)' },
  { value: 'AUD', label: 'AUD - ($)' },
  { value: 'AZN', label: 'AZN - (Manat)' },
  { value: 'BHD', label: 'BHD - (Dinar)' },
  { value: 'BDT', label: 'BDT - (Taka)' },
  { value: 'BBD', label: 'BBD - ($)' },
  { value: 'BYN', label: 'BYN - (Rubel)' },
  { value: 'BZD', label: 'BZD - ($)' },
  { value: 'BMD', label: 'BMD - ($)' },
  { value: 'BTN', label: 'BTN - (Ngultrum)' },
  { value: 'BOB', label: 'BOB - (Boliviano)' },
  { value: 'BAM', label: 'BAM - (Convertible Mark)' },
  { value: 'BWP', label: 'BWP - (Pula)' },
  { value: 'BRL', label: 'BRL - (R$)' },
  { value: 'GBP', label: 'GBP - (£)' },
  { value: 'BND', label: 'BND - ($)' },
  { value: 'BGN', label: 'BGN - (Lev)' },
  { value: 'BIF', label: 'BIF - (Franc)' },
  { value: 'KHR', label: 'KHR - (Riel)' },
  { value: 'CAD', label: 'CAD - ($)' },
  { value: 'CVE', label: 'CVE - (Escudo)' },
  { value: 'KYD', label: 'KYD - ($)' },
  { value: 'XAF', label: 'XAF - (Franc)' },
  { value: 'CLP', label: 'CLP - (Peso)' },
  { value: 'CNY', label: 'CNY - (¥)' },
  { value: 'COP', label: 'COP - (Peso)' },
  { value: 'KMF', label: 'KMF - (Franc)' },
  { value: 'CDF', label: 'CDF - (Franc)' },
  { value: 'CRC', label: 'CRC - (Colón)' },
  { value: 'HRK', label: 'HRK - (Kuna)' },
  { value: 'CUP', label: 'CUP - (Peso)' },
  { value: 'CZK', label: 'CZK - (Koruna)' },
  { value: 'DKK', label: 'DKK - (Krone)' },
  { value: 'DJF', label: 'DJF - (Franc)' },
  { value: 'DOP', label: 'DOP - (Peso)' },
  { value: 'XCD', label: 'XCD - ($)' },
  { value: 'EGP', label: 'EGP - (£)' },
  { value: 'ERN', label: 'ERN - (Nakfa)' },
  { value: 'ETB', label: 'ETB - (Birr)' },
  { value: 'EUR', label: 'EUR - (€)' },
  { value: 'FJD', label: 'FJD - ($)' },
  { value: 'GMD', label: 'GMD - (Dalasi)' },
  { value: 'GEL', label: 'GEL - (Lari)' },
  { value: 'GHS', label: 'GHS - (Cedi)' },
  { value: 'GIP', label: 'GIP - (£)' },
  { value: 'GTQ', label: 'GTQ - (Quetzal)' },
  { value: 'GNF', label: 'GNF - (Franc)' },
  { value: 'GYD', label: 'GYD - ($)' },
  { value: 'HTG', label: 'HTG - (Gourde)' },
  { value: 'HNL', label: 'HNL - (Lempira)' },
  { value: 'HKD', label: 'HKD - ($)' },
  { value: 'HUF', label: 'HUF - (Forint)' },
  { value: 'ISK', label: 'ISK - (Króna)' },
  { value: 'INR', label: 'INR - (₹)' },
  { value: 'IDR', label: 'IDR - (Rp)' },
  { value: 'IRR', label: 'IRR - (Rial)' },
  { value: 'IQD', label: 'IQD - (Dinar)' },
  { value: 'ILS', label: 'ILS - (₪)' },
  { value: 'JMD', label: 'JMD - ($)' },
  { value: 'JPY', label: 'JPY - (¥)' },
  { value: 'JOD', label: 'JOD - (Dinar)' },
  { value: 'KZT', label: 'KZT - (Tenge)' },
  { value: 'KES', label: 'KES - (Shilling)' },
  { value: 'KWD', label: 'KWD - (Dinar)' },
  { value: 'KGS', label: 'KGS - (Som)' },
  { value: 'LAK', label: 'LAK - (Kip)' },
  { value: 'LBP', label: 'LBP - (£)' },
  { value: 'LSL', label: 'LSL - (Loti)' },
  { value: 'LRD', label: 'LRD - ($)' },
  { value: 'LYD', label: 'LYD - (Dinar)' },
  { value: 'MKD', label: 'MKD - (Denar)' },
  { value: 'MGA', label: 'MGA - (Ariary)' },
  { value: 'MWK', label: 'MWK - (Kwacha)' },
  { value: 'MYR', label: 'MYR - (RM)' },
  { value: 'MVR', label: 'MVR - (Rufiyaa)' },
  { value: 'MRU', label: 'MRU - (Ouguiya)' },
  { value: 'MUR', label: 'MUR - (Rupee)' },
  { value: 'MXN', label: 'MXN - ($)' },
  { value: 'MDL', label: 'MDL - (Leu)' },
  { value: 'MNT', label: 'MNT - (Tögrög)' },
  { value: 'MAD', label: 'MAD - (Dirham)' },
  { value: 'MZN', label: 'MZN - (Metical)' },
  { value: 'MMK', label: 'MMK - (Kyat)' },
  { value: 'NAD', label: 'NAD - ($)' },
  { value: 'NPR', label: 'NPR - (Rupee)' },
  { value: 'ANG', label: 'ANG - (ƒ)' },
  { value: 'TWD', label: 'TWD - (NT$)' },
  { value: 'NZD', label: 'NZD - ($)' },
  { value: 'NIO', label: 'NIO - (Córdoba)' },
  { value: 'NGN', label: 'NGN - (Naira)' },
  { value: 'KPW', label: 'KPW - (Won)' },
  { value: 'NOK', label: 'NOK - (Krone)' },
  { value: 'OMR', label: 'OMR - (Rial)' },
  { value: 'PKR', label: 'PKR - (Rupee)' },
  { value: 'PAB', label: 'PAB - (Balboa)' },
  { value: 'PGK', label: 'PGK - (Kina)' },
  { value: 'PYG', label: 'PYG - (Guarani)' },
  { value: 'PEN', label: 'PEN - (Sol)' },
  { value: 'PHP', label: 'PHP - (₱)' },
  { value: 'PLN', label: 'PLN - (Złoty)' },
  { value: 'QAR', label: 'QAR - (Rial)' },
  { value: 'RON', label: 'RON - (Leu)' },
  { value: 'RUB', label: 'RUB - (₽)' },
  { value: 'RWF', label: 'RWF - (Franc)' },
  { value: 'SHP', label: 'SHP - (£)' },
  { value: 'WST', label: 'WST - (Tala)' },
  { value: 'STN', label: 'STN - (Dobra)' },
  { value: 'SAR', label: 'SAR - (Rial)' },
  { value: 'RSD', label: 'RSD - (Dinar)' },
  { value: 'SCR', label: 'SCR - (Rupee)' },
  { value: 'SLL', label: 'SLL - (Leone)' },
  { value: 'SGD', label: 'SGD - ($)' },
  { value: 'SBD', label: 'SBD - ($)' },
  { value: 'SOS', label: 'SOS - (Shilling)' },
  { value: 'ZAR', label: 'ZAR - (R)' },
  { value: 'KRW', label: 'KRW - (₩)' },
  { value: 'SSP', label: 'SSP - (£)' },
  { value: 'LKR', label: 'LKR - (Rupee)' },
  { value: 'SDG', label: 'SDG - (£)' },
  { value: 'SRD', label: 'SRD - ($)' },
  { value: 'SZL', label: 'SZL - (Lilangeni)' },
  { value: 'SEK', label: 'SEK - (Krona)' },
  { value: 'CHF', label: 'CHF - (Franc)' },
  { value: 'SYP', label: 'SYP - (£)' },
  { value: 'TJS', label: 'TJS - (Somoni)' },
  { value: 'TZS', label: 'TZS - (Shilling)' },
  { value: 'THB', label: 'THB - (฿)' },
  { value: 'TOP', label: 'TOP - (Paʻanga)' },
  { value: 'TTD', label: 'TTD - ($)' },
  { value: 'TND', label: 'TND - (Dinar)' },
  { value: 'TRY', label: 'TRY - (₺)' },
  { value: 'TMT', label: 'TMT - (Manat)' },
  { value: 'UGX', label: 'UGX - (Shilling)' },
  { value: 'UAH', label: 'UAH - (₴)' },
  { value: 'AED', label: 'AED - (Dirham)' },
  { value: 'USD', label: 'USD - ($)' },
  { value: 'UYU', label: 'UYU - ($)' },
  { value: 'UZS', label: 'UZS - (Soʻm)' },
  { value: 'VUV', label: 'VUV - (Vatu)' },
  { value: 'VES', label: 'VES - (Bolívar)' },
  { value: 'VND', label: 'VND - (₫)' },
  { value: 'YER', label: 'YER - (Rial)' },
  { value: 'ZMW', label: 'ZMW - (Kwacha)' },
  { value: 'ZWL', label: 'ZWL - ($)' }
];

export const testTargetOptions = [
  { value: 'For My Product', label: 'For My Product' },
  { value: 'For a Competitors Product', label: 'For a Competitors Product' },
]

export const deviceOptions = [
  { value: 'any', label: 'Any' },
  { value: 'mobile', label: 'Mobile' },
  { value: 'desktop', label: 'Desktop' },
];

export const mobileOsOptions = [
  { value: 'any', label: 'Any' },
  { value: 'android', label: 'Android' },
  { value: 'ios', label: 'IOS' },
];

export const desktopOsOptions = [
  { value: 'windows', label: 'Windows' },
  { value: 'macos', label: 'MacOS' },
];
